### PR TITLE
Pass lineNumber and lineSource in changed event

### PR DESCRIPTION
**Pull request by fatihacet**
@deckar01 would you mind taking a look at it?

These changes are needed for us in GitLab [for this MR](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/23938).

I am working on adding the tests. Meanwhile, please give it a try and let me know what you think about it. Thanks 👍

### CODE REVIEW

**Comment by fatihacet** [comment]
> Adding this info to the event would be safe for a minor version release.

Thanks for the quick review. That's exactly what we want to do. Let's keep the changes minimum. 👍 


Also Travis pipeline fails because of the error below. I don't what to do with it. Any idea?

> deckar01-task_list@2.0.1 qunit /home/travis/build/deckar01/task_list
> phantomjs test/run-qunit.coffee http://localhost:4018/test/index.html
> Unable to open file '/dev/stderr'

**Comment by deckar01** [comment]
A jQuery release broke compatibility with phantomjs. Using compatible versions fixed the issue. See #24 for more info. The tests are passing on master now.

**Comment by fatihacet** [comment]
@deckar01 rebased from master, thanks for fixing it 👍

**Comment by deckar01** [comment]
I would like to hold off on merging this until you have logic on the back end that consumes it in case the requirements change. Is it OK if you continue using your fork during development of that GitLab feature?

**Comment by fatihacet** [comment]
Yeah sure. I think it makes sense to wait until the GitLab MR merged so we will have a final decision on the parameters etc. Meanwhile we can use my fork.

**Pull request merged**
